export const SCREEN_LOGIN = 'SCREEN_LOGIN';
export const SCREEN_SIGNUP = 'SCREEN_SIGNUP';
export const SCREEN_DASHBOARD = 'SCREEN_DASHBOARD';
export const SCREEN_PROFILE = 'SCREEN_PROFILE';
export const SCREEN_MESSAGES = 'SCREEN_MESSAGES';
export const SCREEN_NEWSFEED = 'SCREEN_NEWSFEED';
export const SCREEN_NOTIFICATIONS = 'SCREEN_NOTIFICATIONS';
